<?php

// autoload.php generated by Composer
if (!class_exists('Composer\\Autoload\\ClassLoader', false)) {
    require __DIR__ . '/vendor/composer' . '/ClassLoader.php';
}

$loader = new Composer\Autoload\ClassLoader();
$composerDir = __DIR__ . '/vendor/composer';

$map = require $composerDir . '/autoload_namespaces.php';
foreach ($map as $namespace => $path) {
    $loader->add($namespace, $path);
}

$classMap = require $composerDir . '/autoload_classmap.php';
if ($classMap) {
    $loader->addClassMap($classMap);
}

$loader->add('TMG', __DIR__ . '/src');
$loader->add('Igorw', __DIR__ . '/vendor/igorw/src');
$loader->add('Rafal', __DIR__ . '/vendor/rafal/src');

$loader->register();

return $loader;
